spring:
  datasource:
    url: jdbc:h2:mem:testdb
    usename: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      format-sql: true
twilio:
  sid: ${TWILIO_SID}
  key: ${TWILIO_KEY}
  phone:
    from: ${TWILIO_PHONE_FROM}
    to: ${TWILIO_PHONE_TO}
