spring:
  datasource:
    url: jdbc:h2:mem:testdb
    usename: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      format-sql: true